version: '3.8'
services:
    wallet-php:
        container_name: wallet-php
        build:
            context: ./
            dockerfile: images/php/Dockerfile
        ports:
            - "8080:80"
        networks:
            - wallet-network
        volumes:
            - ./config/apache/default.conf:/etc/apache2/sites-enabled/default.conf
            - type: bind
              source: ./src
              target: /var/www/html
    wallet-mysql:
        container_name: wallet-mysql
        platform: linux/x86_64
        image: mysql
        restart: always
        networks:
            - wallet-network
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        volumes:
            - ./storage/mysql:/var/lib/mysql
    wallet-phpmyadmin:
        container_name: wallet-phpmyadmin
        image: phpmyadmin
        networks:
            - wallet-network
        ports:
            - "3305:80"
        restart: always
        environment:
            PMA_HOST: wallet-mysql
            PMA_PASSWORD: ""
        depends_on:
            - wallet-mysql
    wallet-ngrok:
        container_name: wallet-ngrok
        image: wernight/ngrok:latest
        ports:
            - 4040:4040
        environment:
            NGROK_PROTOCOL: http
            NGROK_PORT: wallet-php:80
            NGROK_REGION: eu
            NGROK_AUTH: ${NGROK_AUTH}
        depends_on:
            - wallet-php
        networks:
            - wallet-network
            
volumes:
    src:
networks:
  wallet-network: